<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Microsoft</name>
   <tag></tag>
   <elementGuidId>965336bc-72be-4f60-9b79-66766fcd019a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Microsoft Microsoft&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>80f9830e-8395-4cdd-92b4-bd356b9d4a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-outlined flex items-center gap-2 rounded border border-gray-300 bg-white px-4 py-2 shadow transition duration-200 hover:bg-gray-100</value>
      <webElementGuid>2f6e44aa-1b51-4701-87d6-8807cab20607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p</name>
      <type>Main</type>
      <value>outlined</value>
      <webElementGuid>79e6e628-b4bb-4869-885d-96e6d24619b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da60104f-ca72-4d6d-872b-70345ff6edf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5330d993-ba59-400d-92c0-69e3ebcceb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f13c4f57-9fa4-41c9-99b0-ca7a11906278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>ed58ba80-fa65-46e0-a5b8-6036a7c4fad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pd-ripple</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>768b1876-55b6-4ffc-83a7-5bf669c9e021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Microsoft</value>
      <webElementGuid>3771a899-ff53-482d-b657-b6170bad95b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[1]/div[@class=&quot;flex min-h-screen flex-col items-center justify-center bg-[#EFF3F8] px-4&quot;]/div[@class=&quot;w-full max-w-lg rounded-lg bg-white pt-6 pb-10 px-10 shadow-lg flex flex-col items-center&quot;]/div[@class=&quot;flex gap-4&quot;]/button[@class=&quot;p-button p-component p-button-outlined flex items-center gap-2 rounded border border-gray-300 bg-white px-4 py-2 shadow transition duration-200 hover:bg-gray-100&quot;]</value>
      <webElementGuid>498c70dc-0bef-48bc-bd4b-371b43d21b30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>baa454e7-6583-4e4d-ae0f-caee947f7e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div/div[2]/button</value>
      <webElementGuid>ea0279ab-bdcd-4d3d-9c12-48e38e9b25da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to'])[1]/following::button[1]</value>
      <webElementGuid>6f2d61f7-96f1-47d8-a35f-88b165e5a382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>68d5f861-2912-437d-a61a-3c6385c0ff22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Microsoft' or . = 'Microsoft')]</value>
      <webElementGuid>3d486360-d550-4691-af18-b961c4d478eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
