<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Clear Filters</name>
   <tag></tag>
   <elementGuidId>dc27685c-29a4-445b-9963-00d0021f6b0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='clear-filter-button']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#clear-filter-button > span.p-button-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Clear Filters&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>93d21fa3-e7a6-4408-8007-dea9b3e6728d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button-label</value>
      <webElementGuid>61bb8cc7-c3ec-44ee-b64e-22d7b2f0272a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4b75c5c7-6639-4fa1-b3cd-252d4f0cabc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clear Filters</value>
      <webElementGuid>a269c90a-a86c-4176-94d0-0365fca12b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_2_5_tabpanel_1&quot;)/div[@class=&quot;flex h-full min-h-0 flex-col gap-4&quot;]/div[@class=&quot;flex flex-col gap-4 sm:flex-row sm:items-center&quot;]/button[@id=&quot;clear-filter-button&quot;]/span[@class=&quot;p-button-label&quot;]</value>
      <webElementGuid>6b4d9b94-7d23-476a-8c22-b6ea9df9b90e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='clear-filter-button']/span</value>
      <webElementGuid>9dc825dd-162b-4260-af66-32afdf36d324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by:'])[2]/following::span[3]</value>
      <webElementGuid>abd2fa9c-adb9-416d-868c-223a843d8788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[2]/preceding::span[2]</value>
      <webElementGuid>efd53e24-92b3-445c-9557-2adbe6ee92ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Badlis Count'])[2]/preceding::span[4]</value>
      <webElementGuid>cc2da527-5290-4c94-86ce-f3b46306cfaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/span</value>
      <webElementGuid>b0a4279e-15c1-4617-bbbb-6378a2cb3721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Clear Filters' or . = 'Clear Filters')]</value>
      <webElementGuid>6ce5b46a-22f3-4e17-94a7-5ad3ea8ce86e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
