<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Badlis History</name>
   <tag></tag>
   <elementGuidId>5346da8f-77ed-4bff-addd-4a4bff4b6db7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='badlis-history-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#badlis-history-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Badlis History&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff4e3284-1134-460e-8042-b1d086418009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-tab</value>
      <webElementGuid>9115f2cd-2cd5-47ba-86b9-f57c33dd5ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b84b38ba-a05b-4c00-8f0b-2dc11384d265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>badlis-history-tab</value>
      <webElementGuid>7bce0c1b-3826-4ff9-b855-01b0da591a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8ce23d51-2108-4510-8e00-6d9275dcf2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>5e3ab6c5-2e4b-4d33-948e-717519f79a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f24c0e1e-84a3-4f80-9b58-41e302461bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pv_id_2_5_tabpanel_1</value>
      <webElementGuid>2275a6d0-d0b4-460e-8b49-7773fa1cd337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>05ba8cc2-e693-4b9b-b5b7-083bf690087b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5e9c55e1-29a7-4f2e-a93a-0a9d198dab1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-active</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c12aadb3-3750-4825-8f13-e7119ce4a1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>949dcf81-7e41-475a-aa9d-13db29dee0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pd-ripple</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>120fa6e3-fd3c-4bae-b6c1-e796e2e18adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Badlis History </value>
      <webElementGuid>5044d2ad-4da2-446e-b8ff-973ddee1bd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;badlis-history-tab&quot;)</value>
      <webElementGuid>07ad48ef-aafd-40f8-862b-1da89db37e0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='badlis-history-tab']</value>
      <webElementGuid>052f9dd8-1da4-45bc-8102-55dc356b0c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div[3]/div/div/div/div/div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>225b73fa-6f61-444a-80a2-227d75748c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₱ 150'])[1]/following::button[2]</value>
      <webElementGuid>4b7fe261-f177-4001-824b-2e6a90530b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by:'])[1]/preceding::button[2]</value>
      <webElementGuid>7ef9cade-d24b-4e64-be5d-b860c1fd85ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Badlis History']/parent::*</value>
      <webElementGuid>e3796d2b-21d9-43b3-83ca-a213fe9428ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>42c3a06a-cf31-48dc-a5a6-2aeee540b7af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'badlis-history-tab' and (text() = ' Badlis History ' or . = ' Badlis History ')]</value>
      <webElementGuid>fde6d85e-1171-42bd-b3cc-559eb1defee3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
