<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Microsoft</name>
   <tag></tag>
   <elementGuidId>500e340b-7119-489f-8964-668a073971f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Microsoft Microsoft&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71fd45ff-cc1e-4e5f-9c34-08b555ec9cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-outlined flex items-center gap-2 rounded border border-gray-300 bg-white px-4 py-2 shadow transition duration-200 hover:bg-gray-100</value>
      <webElementGuid>6fa3afc0-c979-44f5-b2a0-a8627b382532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p</name>
      <type>Main</type>
      <value>outlined</value>
      <webElementGuid>c67e87e8-03cb-4879-a908-de87946e9e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16f22890-185a-4850-8800-7c7a6fa3d0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aa0e4196-78b8-447a-a100-0d3b68841064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6f191527-90c4-4453-ac2f-9dcae6fb5c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>0acca5f5-54cb-434b-883e-ea65e9bfc844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pd-ripple</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e5a25167-af79-4a0e-bec8-16523730fb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Microsoft</value>
      <webElementGuid>c062dccc-db3d-4374-b92b-f539cd1eee2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[1]/div[@class=&quot;flex min-h-screen flex-col items-center justify-center bg-[#EFF3F8] px-4&quot;]/div[@class=&quot;w-full max-w-lg rounded-lg bg-white pt-6 pb-10 px-10 shadow-lg flex flex-col items-center&quot;]/div[@class=&quot;flex gap-4&quot;]/button[@class=&quot;p-button p-component p-button-outlined flex items-center gap-2 rounded border border-gray-300 bg-white px-4 py-2 shadow transition duration-200 hover:bg-gray-100&quot;]</value>
      <webElementGuid>18e5478c-1554-4c87-98ed-f61c61b99308</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>a3ded6f9-6f7f-4ae8-b449-56ff06ca6a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div/div[2]/button</value>
      <webElementGuid>348b5fd8-7520-4404-bdf5-e499c286524a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to'])[1]/following::button[1]</value>
      <webElementGuid>fc731923-b8b5-4e4f-bdfd-55fa6f108d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>1bc60429-7abb-4af4-8b06-eaddfc0f2e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Microsoft' or . = 'Microsoft')]</value>
      <webElementGuid>0b54b9d0-42d6-460a-bd91-8f0d1bd6c7df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
