<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm Selected (2)</name>
   <tag></tag>
   <elementGuidId>09eccf6d-d38a-4cc6-8c0a-2bf4d93e36a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='badlis-confirm-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#badlis-confirm-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Confirm Selected (2)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b990215-7873-4b05-9c3e-b6f6cc5a6351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component primary_button w-full sm:w-auto sm:min-w-[9rem]</value>
      <webElementGuid>bad36b9c-bb5c-4f9a-a924-4c11776de763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>17a10fe2-bcd9-445f-9f4d-87c1c9a382de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Confirm Selected (2)</value>
      <webElementGuid>d3106046-c024-40a0-bf16-80d4514c6a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e531c6d1-e16b-4c41-b57a-a71ae10ebc40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>af5eefd5-9fab-479c-91e3-edfcbc1819c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>badlis-confirm-button</value>
      <webElementGuid>92b71fbb-8339-488b-ac83-b27090780fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>72746ca0-d918-4ed6-adc8-4f18c0e3ec6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pd-ripple</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>694e4df6-1687-4f32-bb7e-906369ba2f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm Selected (2)</value>
      <webElementGuid>e3cf0a2e-583e-412b-a1d9-9ece53cab5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;badlis-confirm-button&quot;)</value>
      <webElementGuid>e384d473-8edc-492a-91f4-4aaf58bd13f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='badlis-confirm-button']</value>
      <webElementGuid>7dd06ef4-2087-48da-84a9-f6bc8d85e45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_2_5_tabpanel_0']/div/div/div/div[2]/button</value>
      <webElementGuid>a31db604-0498-4b52-8404-b088fe1ea9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear Filters'])[1]/following::button[1]</value>
      <webElementGuid>e6374972-8a20-4dc5-92fd-88eb97f61996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by:'])[1]/following::button[3]</value>
      <webElementGuid>1790c36a-c309-4ab0-aa9b-208ed9d9d1f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/preceding::button[1]</value>
      <webElementGuid>12ff06f0-a793-4dc6-b1d8-c9357db29d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>28c9b1da-7fac-4f57-b7f9-9724d02940f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'badlis-confirm-button' and (text() = 'Confirm Selected (2)' or . = 'Confirm Selected (2)')]</value>
      <webElementGuid>1a0bc781-38fb-4b1f-aa26-732808c8e3e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
