<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Actions_p-checkbox-input</name>
   <tag></tag>
   <elementGuidId>65ac5baa-7742-4ba2-b5a0-9cae4135fe95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td > div.p-checkbox.p-component.p-variant-filled > input.p-checkbox-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td > .p-checkbox > .p-checkbox-input >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5cc9226-4205-4d90-8f88-1a65903ce8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d848d3ff-5292-4177-94c3-4857ca60f884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-checkbox-input</value>
      <webElementGuid>85e70335-da04-4135-a7d5-6da9dc997b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Row Unselected</value>
      <webElementGuid>c9133838-9d3b-4c70-b50f-0e179ae5ccf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70e89c2e-bf8b-4f75-aed0-4ccc559d48f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_2_5_tabpanel_0&quot;)/div[@class=&quot;flex h-full min-h-0 flex-col&quot;]/div[@class=&quot;flex h-full min-h-0 flex-col gap-4&quot;]/div[@class=&quot;flex min-h-0 flex-1 flex-col overflow-auto&quot;]/div[@class=&quot;flex min-h-0 flex-1 flex-col overflow-auto&quot;]/div[@class=&quot;p-datatable p-component p-datatable-scrollable p-datatable-flex-scrollable badlis-table flex h-full min-h-0 flex-1 flex-col overflow-hidden&quot;]/div[@class=&quot;p-datatable-table-container&quot;]/table[@class=&quot;p-datatable-table p-datatable-scrollable-table&quot;]/tbody[@class=&quot;p-datatable-tbody overflow-auto&quot;]/tr[@class=&quot;p-row-even&quot;]/td[1]/div[@class=&quot;p-checkbox p-component p-variant-filled&quot;]/input[@class=&quot;p-checkbox-input&quot;]</value>
      <webElementGuid>c70c7aca-db27-45c9-a08f-08d4ef84ff5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
      <webElementGuid>6abf5670-293e-4035-8ff9-550f431573df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_2_5_tabpanel_0']/div/div/div[2]/div/div/div/table/tbody/tr/td/div/input</value>
      <webElementGuid>70fbdbe7-ca2b-41d7-b38f-f13e3cd1a54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>62eb4ffc-4779-4ab8-abb8-3690c3991758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>7be0a9a8-364b-4861-bf9b-b6d317632cd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
