<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Clear Filters</name>
   <tag></tag>
   <elementGuidId>fe2081e3-1404-43d9-9535-4d358484739c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clear-filters-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='clear-filters-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Clear Filters&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8dab79ff-0091-4ef7-86d5-1e504fe1faa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-primary rounded px-5 py-2 text-white hover:bg-[#53989f]</value>
      <webElementGuid>7580fbc3-90c7-4e73-8746-5943a1199501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clear-filters-button</value>
      <webElementGuid>e2101bac-7e14-4ace-8a42-c58e85efca75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Clear Filters </value>
      <webElementGuid>981670f3-bb12-4a43-85e4-f2716a5701ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clear-filters-button&quot;)</value>
      <webElementGuid>fd87b00b-359c-4c7c-a631-7381573b0657</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='clear-filters-button']</value>
      <webElementGuid>c7507be2-49d7-4cbf-9ff2-ff0c466d0871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div[3]/div/div/div/div/div[2]/div/div/div/div/div/div/button</value>
      <webElementGuid>e271c51b-e7d2-45c6-9d7b-1af25d72d8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by:'])[1]/following::button[1]</value>
      <webElementGuid>8062ad71-e777-406b-8f8d-7b6e90262892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Name'])[1]/preceding::button[1]</value>
      <webElementGuid>24081c7b-cb22-4009-afbe-854e4dce9630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Position'])[1]/preceding::button[1]</value>
      <webElementGuid>16472805-14f4-47de-a718-4562cbe5245d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clear Filters']/parent::*</value>
      <webElementGuid>9ad38504-547f-467e-8494-62854845b129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/button</value>
      <webElementGuid>ca0829dd-56e4-4f9d-a2ae-e9e4adc51295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'clear-filters-button' and (text() = ' Clear Filters ' or . = ' Clear Filters ')]</value>
      <webElementGuid>80db7edb-1a01-48ab-9565-ed81e7f96337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
