<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Active</name>
   <tag></tag>
   <elementGuidId>7d41ad47-36f9-476c-8bbc-33a2f7263346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employee-status-filter-select_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='employee-status-filter-select_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Active&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c1a8e21a-3043-4ac0-9ccd-fa981220e9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employee-status-filter-select_1</value>
      <webElementGuid>44334bc1-7e1f-4f6b-9fc7-7eb7b3ab48fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-select-option p-select-option-selected p-focus</value>
      <webElementGuid>c25d1531-2a79-47dd-9456-4d5704d901a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>30641977-9780-4fc6-99db-11fad59427d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>c00f2d62-cd37-4b2c-8345-670191c59b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f5e749c-1822-461a-a2e8-fa456ed2d005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>236fbfec-1537-4076-8087-0e041536e2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>45e3a0a0-bbae-4969-89dd-ef369449a3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2b417052-bc1a-4015-acb1-acedf1a0d3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>65939548-949f-48aa-9dbb-9c57f3c75e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>981bb796-0b41-4e79-a64c-c63128e3a462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2c85fcad-d2d0-48b3-a9a4-c3f1b64a03db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>54867eb6-6784-40ec-bdf8-9806a2f5c6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pd-ripple</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>282619c9-b996-4685-a2bc-b5acfbef4642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>7aa16c06-9647-4e16-bd20-fe55a98cf41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employee-status-filter-select_1&quot;)</value>
      <webElementGuid>2d5ee0de-a82a-4121-93e7-42116d63d168</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='employee-status-filter-select_1']</value>
      <webElementGuid>8f552c04-d4f4-44ea-986c-11154edd068b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='employee-status-filter-select_list']/li[2]</value>
      <webElementGuid>518673e0-c8b7-4dda-a772-fc3f240b5377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::li[1]</value>
      <webElementGuid>01c91998-9e84-4514-ae29-2463a4de51cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deactivated'])[2]/preceding::li[1]</value>
      <webElementGuid>94a57c78-8747-4583-b59b-76ee10c307db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]</value>
      <webElementGuid>cdca9273-c17c-44c8-998c-ea096cfa6acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'employee-status-filter-select_1' and (text() = 'Active' or . = 'Active')]</value>
      <webElementGuid>15af0f0c-9919-490f-85c5-8678eb527ae9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
