<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Microsoft</name>
   <tag></tag>
   <elementGuidId>027c8de7-79df-4432-91d0-81b44a813900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Microsoft Microsoft&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87d51756-6af0-46d4-b9ba-cb01b5361fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-outlined flex items-center gap-2 rounded border border-gray-300 bg-white px-4 py-2 shadow transition duration-200 hover:bg-gray-100</value>
      <webElementGuid>10ff0b6f-23be-40f3-9963-c0c170e74a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p</name>
      <type>Main</type>
      <value>outlined</value>
      <webElementGuid>74c145f5-20df-4197-8dac-494b46dc09b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>040f631a-d1c4-4618-a3c8-6721bad22e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4a2fe60-5644-4ff7-95aa-4efe4fbc23a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1bc511de-8e3c-4a9d-bbd0-58cbfe007063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>e03671ba-3401-40eb-a87f-08344747d642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pd-ripple</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc06868a-79c7-4907-95b0-2979393e496e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Microsoft</value>
      <webElementGuid>962ea16b-733d-45c5-a1d0-69e2f8710c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[1]/div[@class=&quot;flex min-h-screen flex-col items-center justify-center bg-[#EFF3F8] px-4&quot;]/div[@class=&quot;w-full max-w-lg rounded-lg bg-white pt-6 pb-10 px-10 shadow-lg flex flex-col items-center&quot;]/div[@class=&quot;flex gap-4&quot;]/button[@class=&quot;p-button p-component p-button-outlined flex items-center gap-2 rounded border border-gray-300 bg-white px-4 py-2 shadow transition duration-200 hover:bg-gray-100&quot;]</value>
      <webElementGuid>4587a4f0-0e66-4e35-ac5f-e83bdd7fa976</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>592f8a2a-c013-4386-be1b-bf0d8e7a5bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div/div[2]/button</value>
      <webElementGuid>73a8750f-7137-4e1e-8344-2a22c262acea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to'])[1]/following::button[1]</value>
      <webElementGuid>334ccef9-bf06-4eef-930f-4a4e752824b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>5bedae33-54a6-4d55-a366-92c25ec08336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Microsoft' or . = 'Microsoft')]</value>
      <webElementGuid>96047091-f4c9-441c-affa-8697c0b451e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
