<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Microsoft</name>
   <tag></tag>
   <elementGuidId>fd4d6325-8467-4469-8bec-7995912d77e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Microsoft Microsoft&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e7c16be-d2d5-4b59-a20d-636b8511d5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-outlined flex items-center gap-2 rounded border border-gray-300 bg-white px-4 py-2 shadow transition duration-200 hover:bg-gray-100</value>
      <webElementGuid>97fb6e94-24f7-4986-9c84-eb7c28d5ad33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p</name>
      <type>Main</type>
      <value>outlined</value>
      <webElementGuid>ed5080bd-7e8f-4a69-8c37-8418f69a9be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>973a237d-e88c-4e57-9bda-08bfa47293b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c26cc946-c830-4128-ab63-1bd527e5f44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cf1b6103-3e74-45bb-8c01-2b01c91c3763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>69924281-e152-4fd4-a920-5a017da4e6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pd-ripple</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2d569d47-cdc9-4f2f-abb2-a73e602f9931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Microsoft</value>
      <webElementGuid>432b55c0-009e-4ba9-991a-d6896b06113e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[1]/div[@class=&quot;flex min-h-screen flex-col items-center justify-center bg-[#EFF3F8] px-4&quot;]/div[@class=&quot;w-full max-w-lg rounded-lg bg-white pt-6 pb-10 px-10 shadow-lg flex flex-col items-center&quot;]/div[@class=&quot;flex gap-4&quot;]/button[@class=&quot;p-button p-component p-button-outlined flex items-center gap-2 rounded border border-gray-300 bg-white px-4 py-2 shadow transition duration-200 hover:bg-gray-100&quot;]</value>
      <webElementGuid>aa28dc45-22f3-47cb-ab66-9cde67d43f8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>c532aae6-dd5c-49e1-ad38-a706bc047a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div/div[2]/button</value>
      <webElementGuid>9667ff16-a70b-41c3-ab7d-86d535402f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to'])[1]/following::button[1]</value>
      <webElementGuid>32ff2449-e96c-4d58-bdda-94bf90217554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c2c35c21-d1d0-4492-993f-10d902da8c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Microsoft' or . = 'Microsoft')]</value>
      <webElementGuid>a1774c3b-968c-4a8e-9ce8-002b093d3e91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
